FROM --platform=$BUILDPLATFORM golang:1.25-alpine AS builder

ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV GOOS=${TARGETOS} \
    GOARCH=${TARGETARCH} \
    GOARM=${TARGETVARIANT}
RUN CGO_ENABLED=0 go build -a -installsuffix cgo -o wrapper .

FROM scratch
LABEL org.opencontainers.image.url="https://github.com/yyewolf/woodpecker-plugins"
LABEL org.opencontainers.image.documentation="https://github.com/yyewolf/woodpecker-plugins/blob/main/README.md"
LABEL org.opencontainers.image.source="https://github.com/yyewolf/woodpecker-plugins"
LABEL org.goci.wrapper="/wrapper"

COPY --from=builder /app/wrapper .
ENTRYPOINT ["/wrapper"]
